//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campeones
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Habilidad1 { get; set; }
        public string Habilidad2 { get; set; }
        public string Habilidad3 { get; set; }
        public string Habilidad4 { get; set; }
        public string Pasiva { get; set; }
    }
}
